apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: certmanager-tls
  annotations:
    docs.jenkins-x.io: https://jenkins-x.io/v3/admin/guides/tls_dns/
  {{- if .Values.cluster.enabled }}
  namespace: kuberhealthy
  {{- end }}
spec:
  runInterval: {{ .Values.runInterval }}
  timeout: {{ .Values.timeout }}
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
          {{- if not .Values.cluster.enabled }}
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    serviceAccountName: kh-tls-check-sa
---
{{- if .Values.cluster.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kh-tls-check-check-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kh-tls-check-role
subjects:
  - kind: ServiceAccount
    name: kh-tls-check-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kh-tls-check-role
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificaterequests
      - certificates
      - clusterissuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - acme.cert-manager.io
    resources:
      - orders
      - challenges
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kh-tls-check-sa
  namespace: kuberhealthy
{{- end }}
{{- if not .Values.cluster.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kh-tls-check-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kh-tls-check-role
subjects:
  - kind: ServiceAccount
    name: kh-tls-check-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kh-tls-check-role
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - certificaterequests
      - certificates
      - challenges
      - clusterissuers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - acme.cert-manager.io
    resources:
      - orders
      - challenges
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kh-tls-check-sa
{{- end }}