apiVersion: cert-manager.io/v1
kind: CertificateRequest
metadata:
  annotations:
    cert-manager.io/certificate-name: tls-pr-1956-2-gke-tls-jenkinsxlabs-com-s
    cert-manager.io/certificate-revision: "1"
    cert-manager.io/private-key-secret-name: tls-pr-1956-2-gke-tls-jenkinsxlabs-com-s-gc8mc
  labels:
    gitops.jenkins-x.io/pipeline: namespaces
    jenkins.io/letsencrypt-service: staging
  name: tls-pr-1956-2-gke-tls-jenkinsxlabs-com-s-wbnsn
  namespace: jx
  ownerReferences:
    - apiVersion: cert-manager.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Certificate
      name: tls-pr-1956-2-gke-tls-jenkinsxlabs-com-s

spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging

status:
  conditions:
    - lastTransitionTime: "2021-01-06T15:50:10Z"
      message: 'All ok'
      reason: Pending
      status: "True"
      type: Ready
