apiVersion: acme.cert-manager.io/v1
kind: Challenge
metadata:
  finalizers:
    - finalizer.acme.cert-manager.io
  name: tls-pr-1956-2-gke-tls-jenkinsxlabs-com-s-wbnsn-45873-291019711
  namespace: jx
  ownerReferences:
    - apiVersion: acme.cert-manager.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Order
      name: tls-pr-1956-2-gke-tls-jenkinsxlabs-com-s-wbnsn-458730623
spec:
  authorizationURL: https://acme-staging-v02.api.letsencrypt.org/acme/foo
  dnsName: pr-1956-2-gke-tls.jenkinsxlabs.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  solver:
    dns01:
      cloudDNS:
        project: jenkins-x-labs-bdd
    selector:
      dnsNames:
        - '*.pr-1956-2-gke-tls.jenkinsxlabs.com'
        - pr-1956-2-gke-tls.jenkinsxlabs.com
  type: DNS-01
  url: https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/foo
  wildcard: true
status:
  presented: false
  processing: false
  reason: Successfully authorized domain
  state: valid